# -*- coding: utf-8 -*-

from odoo import models, fields, api

class alquiler(models.Model):
    _name = 'quintoarte.alquiler'
    _description = 'Alquiler de un marco o cuadro'

    alquiler_id = fields.Integer("", autogenerated=True, readonly=True)
    fecha_inicio = fields.Date("Fecha de inicio", required=True)
    fecha_fin = fields.Date("Fecha de fin", required=True)
    precio_total = fields.Float("Precio total", (10,2), readonly=True, compute="_compute_precio_total")
    observacion = fields.Text("Observación")
    direccion = fields.Char("Dirección")
    
    cuadro_ids = fields.Many2many("quintoarte.cuadro", "cuadro_id", string="Cuadros")
    empleado_id = fields.Many2one("quintoarte.empleado", string="Empleado")
    cliente_id = fields.Many2one("quintoarte.cliente", string="Cliente")

    @api.depends('fecha_inicio', 'fecha_fin', 'cuadro_ids')
    def _compute_precio_total(self):
        for record in self:
            total = 0
            if record.fecha_inicio and record.fecha_fin:
                dias = (record.fecha_fin - record.fecha_inicio).days
                if dias < 0:
                    dias = 0  # Evitar valores negativos
                
                for cuadro in record.cuadro_ids:
                    total += cuadro.precio_unitario * dias  # Suponiendo que el precio es por día
                
            record.precio_total = total