# -*- coding: utf-8 -*-

from odoo import models, fields, api

class cuadro(models.Model):
    _name = 'quintoarte.cuadro'
    _description = 'Un cuadro'

    cuadro_id = fields.Integer("", autogenerated=True)
    titulo = fields.Char("Titulo")
    autor = fields.Char("Autor")
    anyo = fields.Integer("Año")
    ancho = fields.Integer("Ancho")
    alto = fields.Integer("Alto")
    precio_alquiler = fields.Float("Precio alquiler")
    propiedad = fields.Selection([('cliente', 'Cliente'), ('tienda', 'Tienda')], "Propiedad")
    foto = fields.Binary("Foto")
    # alquiler_ids = fields.Many2many('')
    # enmarcado_ids = fields.One2many('', '')